# Generated by Django 4.0 on 2021-12-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_customer_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
